version: '3.1'

services:

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: developer

    adminer:
        image: adminer
        depends_on: 
            - db
        restart: always
        ports:
            - 8081:8080

    app:
        build:
            context: .
            dockerfile: ./RankedElo.Web/Dockerfile
        container_name: rankedeloapp
        depends_on:
            - db
        ports: 
            - 8080:80
        restart: always
